### ISSUE TITLE
Get your IDE setup for flutter

### ISSUE THREAD

**Issue by Stan15** [LassondeVR/site#2]
# Description
Our IDEs (Code Editors) should be setup to work with Flutter. I think it might be easier if we all decided on one IDE to use, to avoid complications/confusions later on. We can discuss/get your thoughts on this in our meeting later.

# Tasks
- [ ] Install flutter
  - Follow the steps in [this link]( https://docs.flutter.dev/get-started/install)
  - Sidenote: You have to install Android Studio to use flutter even if you plan on using another IDE
  - doesn't take too long
- [ ] Install your IDE (we will discuss which IDE we will be using later)
- [ ] Follow the steps in [this link](https://docs.flutter.dev/get-started/editor?tab=vscode) to add Flutter support to your IDE
  - takes even less time
- [ ] Leave a comment below so I know when everyone has completed this task

**Comment by svastiks** [comment]
Completed - Svastik

**Comment by Stan15** [comment]
Update: So we discussed and decided that it's best if we all stick to using Android Studio
