### ISSUE TITLE
Get a test app running

### ISSUE THREAD

**Issue by Stan15** [LassondeVR/site#3]
# Description
This task is to get you familiar with how to create a flutter project, and how to run the flutter project to see the actual website that you are creating.

This test app is just to get you familiar with creating/running flutter projects. You will delete it later.

# Tasks
- [ ] Create a flutter project by typing ``flutter create <project_name>`` in your terminal.
  - NOTE: replace ``<project_name>`` with your actual project name.
  - This should create a folder named ``<project_name>`` in your current directory. This is your flutter project.
- [ ] Open this folder you just created using your code editor
- [ ] Run the flutter project by typing ``flutter run -d chrome`` in your terminal.
  - After running this, you should see a browser window pop up with your flutter web-app displayed on it.
- [ ] Now you can delete the test app you created by deleing the folder containing the flutter project.
- [ ] Leave a comment below so I know when everyone has completed this task
