### ISSUE TITLE
Getting the LassondeVR flutter project running locally

### ISSUE THREAD

**Issue by Stan15** [LassondeVR/site#4]
# Description
The [GitHub repository](https://github.com/LassondeVR/website) which we use for our Flutter website contains a Flutter project identical to the one you created by completing issue #3. We need to get everyone synced up with this shared repository so that we can collaborate on the same application.

# Tasks
- [ ] Clone the GitHub repository for our website
- [ ] Run the app similarly to how we ran the test app in issue #3 
- [ ] Leave a comment down below so I know when everyone has completed this task
