### ISSUE TITLE
Create initial website design

### ISSUE THREAD

**Issue by Stan15** [LassondeVR/site#5]
# Description
We need a starting design for the website to be able to break down the coding tasks to be done and assign it to team members.

# Tasks
- [x] Create a starting design for the website.
- [x] Get feedback from the rest of the team.
- [x] Tweak the design if needed.
- [x] Close this issue when done. (There should be a "close issue" button below)

# Notes
Keep in mind that this is a starting point that we will build on eventually, so while having a nice starting design is good, don't feel like you have to design the most complex app, right from the get-go

**Comment by Stan15** [comment]
Alright, I'm closing this issue as Ghazal and Adil have worked up a great starting design.

[Here's the link](https://www.canva.com/design/DAFRtKZKZbQ/LkZylmfUacXJHzcoma4Srw/view?utm_content=DAFRtKZKZbQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink) to it for reference.
