### ISSUE TITLE
Create tasks from initial website design

### ISSUE THREAD

**Issue by Stan15** [LassondeVR/site#6]
# Description
After @gigirhmn is done with the initial design, we need to divide work amongst team members to create the design in code

# Tasks
- [ ] Break up website design into components.
- [ ] Write up GitHub issues for creating each of these components.
- [ ] Have a meeting to discuss who works on what issue.
- [ ] Assign team members to GitHub issues accordingly.
